# Generated by Django 4.0.4 on 2022-04-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Certificaciones',
                'verbose_name_plural': 'Certificaciones',
            },
        ),
        migrations.AlterModelOptions(
            name='estudiantes',
            options={'verbose_name': 'Estudiantes', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'profesores'},
        ),
    ]
